#!/usr/bin/python3
# 08/27/2020 - Created by Sahil Gulyani
import re
from collections import Counter
with open(r'./logfile') as f:
    loglines=f.read()

regex=re.compile(r'(?:\d{1,3}\.){3}\d{1,3}')
iplst=regex.findall(loglines)
ipdct_Cnt=dict(Counter(iplst))
top_ips=sorted(ipdct_Cnt.items(), key=lambda x: x[1], reverse=True)
for ips in top_ips[:8]:
    print(*ips, sep=' ')
